### ISSUE TITLE
Docker support for JIRA EAP releases

### ISSUE THREAD

**Issue by JensPiegsa** [cptactionhank/docker-atlassian-jira#12]
This is a great image! You may consider to also provide docker tags for the EAP releases ([Early Access Program](https://de.atlassian.com/software/jira/download-eap)).

The download URL follows the same pattern, so an update of your version variable may do the trick (`ENV JIRA_VERSION  7.0.0-m01`).

**Comment by JensPiegsa** [comment]
Well, the current EAP version seems to be restricted to the Oracle JVM.

**Comment by cptactionhank** [comment]
is there a way to easily programmatically detect if there is a new EAP version available?

**Comment by JensPiegsa** [comment]
You could use `jq` to read the output of `https://my.atlassian.com/download/feeds/eap/jira.json`.

The download url can be obtained by:

```sh
curl https://my.atlassian.com/download/feeds/eap/jira.json -Ls \
| cut -b 11- | rev | cut -c 2- | rev \
| jq -r '.[] | select(.zipUrl | contains("tar")) | select(.description|contains("WAR") | not) | .zipUrl'
```

and the version number with:

```sh
curl https://my.atlassian.com/download/feeds/eap/jira.json -Ls \
| cut -b 11- | rev | cut -c 2- | rev \
| jq -r '.[] | select(.zipUrl | contains("tar")) | select(.description|contains("WAR") | not) | .version'
```
Nevertheless this would require a rebuild of your Docker image.

**Comment by cptactionhank** [comment]
I have made an `eap` branch which should support building the latest version of the EAP preview, but the Docker hub has a bug in the automated build settings, so I cannot yet create a tag for EAP on my Docker repository. Feel free to have a look at the branch, give comments or send me a pull request with improvements.

**Comment by JensPiegsa** [comment]
Great work. Thanks for this contribution.

**Comment by cptactionhank** [comment]
JIRA and Confluence EAP versions are live btw.
