### ISSUE TITLE
localhost:8080 is loading forever

### ISSUE THREAD

**Issue by computerlyrik** [cptactionhank/docker-atlassian-jira#13]
using your fastlane-start command on archlinux 
Docker version 1.8.1, build d12ea79

**Comment by cptactionhank** [comment]
Have you checked the docker container log? JIRA is memory happy, are you using a machine with a low amount of memory and a slow machine? My home server takes about 1-2 minutes to boot JIRA on a 1.2GHz Atom with 4GB ram

**Comment by computerlyrik** [comment]
Yes, the log says, jira is starting happily.

Core i7 ... i will try again and wait a little.

It works for you on a fresh installed env?


Am 23.08.2015 um 15:23 schrieb Martin Jensen:

**Comment by cptactionhank** [comment]
I do perform acceptance tests, which run through the setup process and testet that it can get to the JIRA dashboard.

The acceptance tests wait's to create web requests until the regular expression `Server startup in \d+ ms` is found in the log output, which is when tomcat has bootet JIRA and ready to serve. Could you supply the container log output?

**Comment by computerlyrik** [comment]
Yes, this is the tailed log output:

```bash
2015-08-27 19:20:36,874 localhost-startStop-1 INFO      [jira.config.database.DatabaseConfigurationManagerImpl] The database is not yet configured
2015-08-27 19:20:36,874 localhost-startStop-1 INFO      [jira.config.database.DatabaseConfigurationManagerImpl] Enqueuing Post database-configuration launchers on post-database-activated queue
2015-08-27 19:20:36,896 localhost-startStop-1 INFO      [atlassian.jira.startup.LauncherContextListener] Memory Usage:
---------------------------------------------------------------------------------
  Heap memory     :  Used:   50 MiB.  Committed:  462 MiB.  Max:  718 MiB
  Non-heap memory :  Used:   53 MiB.  Committed:   55 MiB.  Max: 1264 MiB
---------------------------------------------------------------------------------
  TOTAL           :  Used:  103 MiB.  Committed:  516 MiB.  Max: 1982 MiB
---------------------------------------------------------------------------------
Aug 27, 2015 7:20:37 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-apr-8080"]
Aug 27, 2015 7:20:37 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 8666 ms
```
realyy fast, but still loading on 8080 forever.

Yes, other machines work. (of course all stopped before testing)

**Comment by cptactionhank** [comment]
Then i'm afraid i don't really know what to suggest, perhaps try another browser? can you reproduce the problem for example in a vagrant example or a fresh VM.

**Comment by cptactionhank** [comment]
Any news on this?

**Comment by computerlyrik** [comment]
Seems to be an issue on docker networking.
Effects other containers now, too.

Thanks for your help!

Closing ...
