### ISSUE TITLE
Jira Software (v7)

### ISSUE THREAD

**Issue by xeor** [cptactionhank/docker-atlassian-jira#15]
It looks like Jira + Agile is now called jira software, and is also Jira 7.
Basicly, there is now Jira Core, Jira Software and the one with ServiceDesk.

See https://blogs.atlassian.com/2015/10/introducing-jira-software/ for more info.
I can't currently get Agile to work with this docker-container, which is the root cause of this issue.
Are you going for the "core" version of jira in the future? Or this bundle? Or the one that bundles everyone?

**Comment by cptactionhank** [comment]
That's a good question. Until JIRA 7 get released i'm kinda confused whether JIRA Software and JIRA ServiceDesk are going to be plugins or separate instances or installations. I don't think the issue of how exactly the extensions are going to work are being thoroughly described to make a final decision. They also stated that one's JIRA Core can be extended with JIRA Software and work in one package, which to me indicates that they will be plugins.

Anyway my current plans is to is to have the `atlassian-jira` and `#.#.#` version tags to be the old JIRA and JIRA Core for 7.0 and up. What i'm still not decided on is if i am going to create a new image ie. `atlassian-jira-software` or perhaps just a tag ie. `atlassian-jira:7.0-software`. There are also considerations to be made about bundled versions in the image of Core, Software and ServiceDesk, for tagged versions for example will we need to make all combinations for support all JIRA versions ie. 
```
atlassian-jira:7.0
atlassian-jira:7.0-software
atlassian-jira:7.0-servicedesk
atlassian-jira:7.0-software-servicedesk
```

I haven't had time to play around with the EAP version other than package it in a Docker image, so i'm not sure I can help you at this time. Final decision on the setup, etc. will be decided after the Atlassian Summit or when the 7.0 suite is announced.

**Comment by xeor** [comment]
Thanks for the insight!

Guess we are in Jira-limbo atm.. Looks like it was released a couple of days ago. See https://confluence.atlassian.com/jirasoftware/jira-software-7-0-0-release-notes-776997721.html
But I guess they will come out with more info at the summit.

Thanks for your wonderful container work!

**Comment by cptactionhank** [comment]
Thank you very much :)

I can actually see that 7.0 has been released and i will look into this and get my automation updated accordingly for the new JIRA product split. I have no ETA yet, but i'll look into it when i have free time.

**Comment by cptactionhank** [comment]
Hi,

The repository and automation has now been updated to install JIRA Core as the default image in the `cptactionhank/atlassian-jira` container image.

To install JIRA Software additions you can extend the running container instance by downloading JIRA Software [here](https://marketplace.atlassian.com/plugins/com.atlassian.jira.jira-software-application/versions) as a plugin.

**Comment by xeor** [comment]
wow! That didn't take long! :)
If only I could find a donate button, I would have bought you a beer!

**Comment by cptactionhank** [comment]
Must look into that then :) thank you.
