### ISSUE TITLE
Support for JIRA-Software

### ISSUE THREAD

**Issue by anton-matosov** [cptactionhank/docker-atlassian-jira#16]
Are there any plans to add support for JIRA-Software package any time soon?

**Comment by cptactionhank** [comment]
It's planned to come very soon

**Comment by adc-amatosov** [comment]
Great!!
Appreciate that!

**Comment by cptactionhank** [comment]
Have a look at https://hub.docker.com/r/cptactionhank/docker-atlassian-jira-software/

**Comment by adc-amatosov** [comment]
Thanks! Will try it out today!!

**Comment by cptactionhank** [comment]
Great, thanks. Let me know if something fails, it is tested with my acceptance test suite.

--
Kind regards,

Martin Jensen
