### ISSUE TITLE
Unknown system variable 'storage_engine'

### ISSUE THREAD

**Issue by ctmnz** [cptactionhank/docker-atlassian-jira#23]
When I try to setup jira with mysql I get this error: 

Error connecting to database
Unknown system variable 'storage_engine'

I use mysq:5.7 for the db container

**Comment by cptactionhank** [comment]
I don't think it's a problem with JIRA, can you provide some more information about your setup and error message. Make sure to use the supported software (perhaps MySQL 5.6) and follow the setup and requirement information from Atlassian.

You can checkout the repository on how I setup a MySQL database for acceptance testing.

**Comment by ctmnz** [comment]
It looks like it is connected somehow with Jira  :)
https://confluence.atlassian.com/confkb/confluence-fails-to-start-with-error-unknown-system-variable-storage_engine-using-mysql-5-7-x-789090576.html

**Comment by cptactionhank** [comment]
Yes indeed, JIRA fails because you are not using supported software. Have a look at https://confluence.atlassian.com/adminjiraserver070/supported-platforms-749382629.html or find the equivalent page for the version you are using.

**Comment by ctmnz** [comment]
Using mysql 5.7 is the problem.

http://dev.mysql.com/doc/refman/5.7/en/mysql-nutshell.html

> Removed features:
> The storage_engine system variable. Use default_storage_engine instead.
