### ISSUE TITLE
Has your website been hacked?

### ISSUE THREAD

**Issue by gerrat** [cptactionhank/docker-atlassian-jira#26]
https://cptactionhank.github.io/docker-atlassian-jira/#configuring-system-properties:

This doesn't look like very helpful documentation:

> Physical vehicle A.I. corrupted Legba-ware franchise city plastic human. Long-chain hydrocarbons kanji convenience store nano-faded semiotics sensory Kowloon sunglasses into papier-mache spook youtube denim. Beef noodles vehicle spook systemic smart-concrete skyscraper kanji nodality.

**Comment by cptactionhank** [comment]
Thank you for your convert, It's just some weird mumble filler text, writing text is hard, writing code is easy. Hopefully at some point it will get some TLC, but I haven't had free time to work on this.
