### ISSUE TITLE
Older Postgres ODBC driver blocking engagement with Postgres 9.6

### ISSUE THREAD

**Issue by duncanplatt** [cptactionhank/docker-atlassian-jira#28]
I spinned up this image today as a first experience with Docker (yay!).

In the process, I also used a Postgres docker image, which happened to be the latest, 9.6.1.

I consistently kept getting the error when setting up the admin account: "Cannot create user, all the user directories are read-only".

Users on the Atlassian support noted that using the latest ODBC driver resolved this for them:
- https://answers.atlassian.com/questions/32534340/jira-7-setup-all-user-directories-are-read-only
And similarly for Confluence:
- https://jira.atlassian.com/browse/CONF-44216?src=confmacro 

I have been able to fix this for Jira Core by replacing **_postgresql-9.1-903.jdbc4-atlassian-hosted.jar_** in folder /opt/atlassian/jira/lib with postgresql-9.4.1212.jar from the Postgres JDBC download page, https://jdbc.postgresql.org/download.html

I hope this can be something added to a newer version of the image in future.

Thanks for a great image!

**Comment by cptactionhank** [comment]
I will consider this, however please note that Postgres 9.6 is not a supported database according to Atlassian and this is not supported by them anyways.

https://confluence.atlassian.com/adminjiraserver072/supported-platforms-828787550.html

**Comment by cptactionhank** [comment]
@fmauNeko has kindly provided a pull request that will be used for LATEST and future versions. For current image backport we would need to compile which versions began to support Postgres 9.4 and up.
