### ISSUE TITLE
Upgrading to a new JIRA version

### ISSUE THREAD

**Issue by noonien** [cptactionhank/docker-atlassian-jira#3]
New minor versions of JIRA appear to be released every 2 weeks, however, the [upgrade process](https://confluence.atlassian.com/display/JIRA/Upgrading+JIRA) is kind of convluted.

How do you upgrade your instance of JIRA? Do you follow the upgrade process described in the docs?

What do you think about automating the process?

**Comment by cptactionhank** [comment]
Hello, for now I have been successful in just using the same home directory and database. My container has host mounted the home directory and running with an external postgresql database, so my upgrade procedure has for now been just to run a new container with a newer image and same home mount and external database. In short; after following the upgrade process described in the JIRA documentation once I've been to lazy to carefully read and follow their instructions.

It's surely not best practice but depending on whom the usage is concerned for me as a private person it has been working out just fine. 

I'm not sure how to automate the upgrade proces and also it probably should also be tested, but how? and there comes things to play, for instance is the upgrade a single increment or larger in the version number ie. x.y.5 => x.y.6 or x.y.1 => x.y.6. It's likely not something that should be implemented in the container, but as a server maintenance tool/script which has the notion of how to use docker containers and running JIRA.

Your are welcome to propose a possible solution to this, I'm thinking it would be a documentation issue describing how to manage following upgrade notes for the new JIRA version and applying it with a docker context. Perhaps some wiki pages could be created for this and you are welcome to write up a draft :+1: :smile:

**Comment by noonien** [comment]
I've got the same setup as you, but didn't think of just using the same DB and home because I don't know if JIRA automatically migrates the DB schema/other data, if it does, I see no reason your current upgrade process would not work for future version, this needs some investigation.

Basically, to perform an upgrade as specified in the docs, one needs to perform the following steps:

1.  Stop user access to JIRA
2. Export XML
3. Stop JIRA
4. Backup home and settings files from the installation directory
5. Install new version of JIRA
6. Copy home
7. Copy config files
8. Setup new db for JIRA
9. Import XML data
10. Start JIRA

Steps 4-7 are handled using volumes and simply running a new version of your dockerized JIRA.

Steps 1, 3, 8, 10 can be handled by a script in the container that tell when a new version of the dockerized JIRA is running trough a unix socket in the volume, and can setup placeholder pages while JIRA is down.

The only problem I see is steps 2 and 9, exporting/importing the XML db is done trough the web interface,  a POST request might solve this, but it requires a user with administrative rights, also, the documentation states this process might take a while to complete.

Regarding upgrade compatibility, I don't see a reason to support anything else than consecutive versions to test the upgrading script, otherwise, one should read [the docs](https://confluence.atlassian.com/display/JIRA/Upgrading+JIRA+Manually#UpgradingJIRAManually-1.Beforeyoustart) before upgrading to a new version of JIRA.

This process should be enough to upgrade JIRA by just running a container with a newer version of the dockerized JIRA. Of course an external script might build upon this process, to automate upgrades when a newer version is released, but this is outside the scopes of this issue for now.

**Comment by cptactionhank** [comment]
I have no real experience in upgrading JIRA other than the careless method for my personal use of JIRA, but the upgrades has been through the versions i have on my docker hub and I have not experienced any problems with this.

I don't really have time to look into how to perform an upgrade "properly" or following the official docs, if you ever create a script to make the upgrade process more easy and safe, you are most welcome to make a pull request or write some documentation and I will happily have a look at it and merge it in.

**Comment by soupdiver** [comment]
@noonien 
Steps 2 & 10 can be done via a database export/import I think.
You could export the current databases data but not the structure.
Create a new db container, create the new database structure and import the data.

I'm not sure about how structure changes are handled by JIRA.

**Comment by cptactionhank** [comment]
Closed due to inactivity

**Comment by joskuijpers** [comment]
@soupdiver If one can just export/import the database directly, then what is the point of doing so? If steps 4-7 are handled by using volumes, then all you need to do is exactly what @cptactionhank does: run a new container over the same data.

**Comment by joskuijpers** [comment]
@cptactionhank did this upgrade method also work for you when upgrading from 6 to 7.0.2 Software using your atlassian-jira-software dockerfile?

**Comment by cptactionhank** [comment]
I haven't done this yet myself, so I won't know if this works my own sysops has been postponed a bit so i'm still latest version in the 6 series.

The image aims to be as unopinionated as possible and thus upgrading by just using a new image version corresponds to installing a new version of the software configured to use the same home directory and database.
