### ISSUE TITLE
Alpine variant?

### ISSUE THREAD

**Issue by starlightknight** [cptactionhank/docker-atlassian-jira#37]
Have you considered making an Alpine variant of these images available? Since your images are already based off of java:8, making an alpine variant is very simple.

I was able to make a fully functioning alpine variant of the jira container with a few minor tweaks to the Dockerfile, and I shrunk the container footprint from ~1.02GB -> 488MB, cutting the storage burden by more than half.

Three main tweaks are required:

1. Extend openjdk:8-alpine instead of java:8
2. Convert apt-get entries -> alpine's apk package manager
3. Created a dedicated jira user/group

*Note: This user has uid 100:1000. If you moved to this image and had persistent storage on a volume, you may have to fix permissions with chown -R 100:1000, but I was otherwise able to cut over seamlessly.

Everything seems to work fine with half the storage burden.

```
FROM openjdk:8-alpine

# Configuration variables.
ENV JIRA_HOME     /var/atlassian/jira
ENV JIRA_INSTALL  /opt/atlassian/jira
ENV JIRA_VERSION  7.3.1

# Install Atlassian JIRA and helper tools and setup initial home
# directory structure.
RUN set -x \
    && apk --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main --repository http://dl-cdn.alpinelinux.org/alpine/edge/community add coreutils sed bash curl tar xmlstarlet tomcat-native \
    && addgroup jira \
    && adduser -S -G jira jira \
    && mkdir -p                "${JIRA_HOME}" \
    && mkdir -p                "${JIRA_HOME}/caches/indexes" \
    && chmod -R 700            "${JIRA_HOME}" \
    && chown -R jira:jira      "${JIRA_HOME}" \
    && mkdir -p                "${JIRA_INSTALL}/conf/Catalina" \
    && curl -Ls                "https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-core-${JIRA_VERSION}.tar.gz" | tar -xz --directory "${JIRA_INSTALL}" --strip-components=1 --no-same-owner \
    && curl -Ls                "https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.38.tar.gz" | tar -xz --directory "${JIRA_INSTALL}/lib" --strip-components=1 --no-same-owner "mysql-connector-java-5.1.38/mysql-connector-java-5.1.38-bin.jar" \
    && rm -f                   "${JIRA_INSTALL}/lib/postgresql-9.1-903.jdbc4-atlassian-hosted.jar" \
    && curl -Ls                "https://jdbc.postgresql.org/download/postgresql-9.4.1212.jar" -o "${JIRA_INSTALL}/lib/postgresql-9.4.1212.jar" \
    && chmod -R 700            "${JIRA_INSTALL}/conf" \
    && chmod -R 700            "${JIRA_INSTALL}/logs" \
    && chmod -R 700            "${JIRA_INSTALL}/temp" \
    && chmod -R 700            "${JIRA_INSTALL}/work" \
    && chown -R jira:jira      "${JIRA_INSTALL}/conf" \
    && chown -R jira:jira      "${JIRA_INSTALL}/logs" \
    && chown -R jira:jira      "${JIRA_INSTALL}/temp" \
    && chown -R jira:jira      "${JIRA_INSTALL}/work" \
    && sed --in-place          "s/java version/openjdk version/g" "${JIRA_INSTALL}/bin/check-java.sh" \
    && echo -e                 "\njira.home=$JIRA_HOME" >> "${JIRA_INSTALL}/atlassian-jira/WEB-INF/classes/jira-application.properties" \
    && touch -d "@0"           "${JIRA_INSTALL}/conf/server.xml"

# Use a specified service account
USER jira:jira

# Expose default HTTP connector port.
EXPOSE 8080

# Set volume mount points for installation and home directory. Changes to the
# home directory needs to be persisted as well as parts of the installation
# directory due to eg. logs.
VOLUME ["/var/atlassian/jira", "/opt/atlassian/jira/logs"]

# Set the default working directory as the installation directory.
WORKDIR /var/atlassian/jira

COPY "docker-entrypoint.sh" "/"
ENTRYPOINT ["/docker-entrypoint.sh"]

# Run Atlassian JIRA as a foreground process by default.
CMD ["/opt/atlassian/jira/bin/catalina.sh", "run"]
```

**Comment by cptactionhank** [comment]
Nice work. 

It is something I have considered but not gotten as far as testing this nor checked if there's compatibility issues using the Alpine distribution.

**Comment by marton78** [comment]
Hi, thanks for this, it works like a charm! To make it even slimmer, you can use the JRE instead of the JDK: `FROM openjdk:8-jre-alpine`

**Comment by cguentherTUChemnitz** [comment]
Are there plans to integrate this as an alpine branch in github and as an alpine tag in dockerhub? It would be nice to see this integrated into the existing software tests.

**Comment by cguentherTUChemnitz** [comment]
I think a switch to alpine based images should be considered more certainly, because atlassian itself is using alpine base images for their confluence server deployment:
https://hub.docker.com/r/atlassian/confluence-server/~/dockerfile/

**Comment by starlightknight** [comment]
I've been running with this config + the equivalent jira config I posted since before I opened this issue. To date I've never experienced any issues with it.

**Comment by marton78** [comment]
You can check my repository, https://github.com/marton78/atlassian based on @cptactionhank's work. All images use Alpine, Oracle Java (as required by Atlassian) and Tomcat Native.

**Comment by cptactionhank** [comment]
Newest image and further versions will be using the Alpine based base image
