### ISSUE TITLE
provide a preconfigured image

### ISSUE THREAD

**Issue by ssbarnea** [cptactionhank/docker-atlassian-jira#38]
As I want to use the Jira image only for Jira API testing purposes it would be really helpful to have an image that doesn't need any further configuration in order to be accessible via Jira REST API.

Would it be possible?

**Comment by cptactionhank** [comment]
Not really, it would require you to have a already commissioned database and a configured `dbconfig.xml` you mount on container creation.

I would recommend you using Atlassian SDK for this purpose which is really better suited for your scenario.

**Comment by ssbarnea** [comment]
I tried using Atlassian SDK in the past but it doesnt really work well for few reasons: maven download of artefacts takes forever and exceeds Travis CI build duration. At this moment I am using a cloud instance for testing, one provided by Atlassian. I had go adapt the tests sonthey can all run against the same live instance. Far from perfect but at least I can start the tests right away. One problem is that this instance is upgraded by Atlassian and I hit lots of failured that are caused by them: Mostly bugs in jira and sometimes api changes.

**Comment by cptactionhank** [comment]
You should look into dependency caching with your CI provider for speeding up Maven use. See https://docs.travis-ci.com/user/caching/

Other than that you can run the setup eg. evaluation using the internal database, copy the database and `dbconfig.xml` out of the container. Have these in your repository and when creating a new container mount the database and `dbconfig.xml` into said container and it should just start and be ready. Be aware of license expiry problems and that another reason why eg. `altas-run-standalone --product jira` should be used.

**Comment by tomskip123** [comment]
a way around this could be to provide execution access to the jira configuration tool in the bin dir of the installation dir. of which at the moment you can't access due to root restrictions...
