### ISSUE TITLE
Upgrading jira

### ISSUE THREAD

**Issue by ChrisWesterfield** [cptactionhank/docker-atlassian-jira#39]
Hi,
Ever Trier to Upgrade jira from Version 7.0 to 7.1
Does this work?
I am considering moving from an Static Instanzen to docker because of the easier scalling in instances (Running an more by using the scalling feature of docker)

**Comment by matiasdecarli** [comment]
+1

**Comment by cptactionhank** [comment]
First of all the upgrade procedure is the exact same as the Atlassian documentation steps for upgrading. You can find their upgrading instructions on their website.

It can be very easy depending on what versions you’re upgrading to and how much of a thrill seeker you are. For example in my instance I do the following (not at all recommended for business, critical, or sensitive data):

1. Copy the atlassian-home to a directory on the host computer
2. Copy the database on my respective database server (eg. postgres)
3. Create a new container with host mounted volume to the containers product home folder
4. Cross my fingers there’s no incompatibility issues. I believe the rule of thumb is that you can auto upgrade between each major version.
