### ISSUE TITLE
JIRA can't create a lock for your jira.home directory

### ISSUE THREAD

**Issue by cvandome** [cptactionhank/docker-atlassian-jira#54]
Hello all,

I've a wired issue, my Jira setup mount a nfs volume for Jira Home, on the first start, files are written to NFS share with the right user (daemon or uid 1 on server side), the .lock_file is also written but Jira show me this error.

I don't understand, if someone could help me.

Here is the NFS Export line from the server:
/nfs/exports/jira-home  192.168.205.0/24(rw,async,no_subtree_check,no_root_squash)

Thanks !

**Comment by cptactionhank** [comment]
Don't know anything about NFS sorry, but what error does JIRA show?

**Comment by cvandome** [comment]
Thanks for reply, Jira show on the webui: JIRA can't create a lock for your jira.home directory

It's wired because when I look inside the NFS folder, I see that Jira can write in this folder.

**Comment by cptactionhank** [comment]
Just delete the existing lock if you are sure no other instances are using the home folder and restart Jira :-) it probably wasn’t deleted due to a hard shutdown or a backup of the home directory was made while JIRA was running.

Kind regards,

Martin Jensen

**Comment by cvandome** [comment]
I've already tested this but no success :(

I'll continue to inspect and come back to post answer here, it can helps.

Best regards

Cédric Vandôme

**Comment by noplaying** [comment]
When I update docker image and restart ,I got "Setup: JIRA couldn't create the jira.home directory“ issue. try find the "lock" file to delete,I faild. where can I find it. can anyone help me? it drive me crazy .

**Comment by iahmad-khan** [comment]
Same issue

**Comment by iahmad-khan** [comment]
Problem solved by remove the symlink of indexes and re-put it in nfs 

unlink /nfs/web-hx/coresrv/projects/jira/dev/jira_home/caches/indexes

**Comment by iahmad-khan** [comment]
Can also be solved by running the container as previlged

**Comment by cvandome** [comment]
hello @iahmad-khan I've fixed issue with NFS config also, it's a NFS side issue

For help it works for me:

On every NFS client:
yum install nfs-utils nfs-utils-lib
systemctl enable rpcbind
systemctl enable nfs-lock
systemctl enable nfs-idmap
systemctl start rpcbind
systemctl start nfs-lock
systemctl start nfs-idmap

In each /etc/fstab client:
192.168.X.X:/nfs/exports    /data   nfs rw,sync,hard,intr 0 0

We can close this issue

**Comment by iahmad-khan** [comment]
hi , 

I have already these packages installed and mount configured , but it stops working when i create a symlink for indexs directry to local file system , and permissions are granted to the user on that local directory where indexes are pointing to from nfs.

**Comment by iahmad-khan** [comment]
so this problem occurs when we symlink indexs dir to local file system and keep the hore dir on nfs

**Comment by cvandome** [comment]
sorry but each NFS probleme is very specific and is out of scope of this issue.

Good luck !

**Comment by cptactionhank** [comment]
If you're using `latest`the UID has changed caused by moving to Alpine as base image
