### ISSUE TITLE
JIRA_HOME volume dir is mounted as root:root instead of daemon:daemon

### ISSUE THREAD

**Issue by kalise** [cptactionhank/docker-atlassian-jira#55]
Hello strange issue here: when starting the jira image as kubernetes pod, the JIRA_HOME volume dir is mounted as `root:root` instead of `daemon:daemon`. This only happens when the volume is mounted on a block device, eg. an external disk or iSCSI. It does not happens when the volume is mounted on a file system share as NFS or GlusterFS.

```
kubectl get pods
NAME                                        READY     STATUS        RESTARTS   AGE
jira-78df8bdcc-sgtbv                        0/1       Running       0          14s

kubectl exec -it jira-78df8bdcc-sgtbv bash
daemon@jira-78df8bdcc-sgtbv:/var/atlassian/jira$ ls -l
total 0
daemon@jira-78df8bdcc-sgtbv:/var/atlassian/jira$ cd ..
daemon@jira-78df8bdcc-sgtbv:/var/atlassian$ ls -lr
total 0
drwxr-xr-x 2 root root 6 Dec  5 17:10 jira
```

The container fails to start because it is not able to access its home directory (permission denied ERROR). Any idea?

**Comment by ElusiveMind** [comment]
I am not sure what OS you are running on, but some OS (like macOS) treat permissions on external file systems differently than they do on something like NFS. NFS has tighter access controls with permissions (if configured to do so) as does access on the main boot drive of the system. I do not know if Linux or Windows is the same way.

**Comment by iBrotNano** [comment]
I had the same problem with Docker Compose. I used the nocopy flag.

`volumes:
      - type: volume
        source: jira-home
        target: /var/atlassian/jira
        volume:
            nocopy: true`

It works without the flag. I don't know if it is related to this problem. I'm not an expert in Docker, but maybe it helps someone.
