### ISSUE TITLE
Failed to create application links

### ISSUE THREAD

**Issue by meyerf99** [cptactionhank/docker-atlassian-jira#57]
Hello Martin

First of all i want to say thank you for the nice atlassian docker containers.
I got errors when i want to create some new application links for confluence and bitbucket.
Maybe you know that issue and can help me?

My Setup:
I use traefik for https:// and all 3 atlassian applications are running on the same docker host.

Docker code:
**JIRA**
>docker run -d 
--restart always \
--name "jira.flavio-meyer.ch" \
-l traefik.backend=jira \
-l traefik.frontend.rule=Host:jira.flavio-meyer.ch \
-l traefik.docker.network=proxy \
-l traefik.port=8080 \
-e X_PROXY_NAME=jira.flavio-meyer.ch \
-e X_PROXY_SCHEME=https \
-e X_PROXY_PORT=443 \
-p 8080:8080 \
--network="internal" \
--network="proxy" \
--volume "/docker/atlassian/jira/data:/var/atlassian/jira" \
--link mysql_atlassian:mysql_atlassian \
--env "CATALINA_OPTS= -Datlassian.plugins.enable.wait=300" \
cptactionhank/atlassian-jira-software:latest

**Confluence**
>docker run -d \
--restart always \
--name "confluence.flavio-meyer.ch" \
-l traefik.backend=confluence \
-l traefik.frontend.rule=Host:confluence.flavio-meyer.ch \
-l traefik.docker.network=proxy \
-l traefik.port=8090 \
-e X_PROXY_NAME=confluence.flavio-meyer.ch \
-e X_PROXY_SCHEME=https \
-e X_PROXY_PORT=443 \
-v "/docker/atlassian/confluence:/var/atlassian/confluence" \
-p 8090:8090 \
--network="internal" \
--network="proxy" \
--link mysql_atlassian:mysql_atlassian \
--env "CATALINA_OPTS=" \
cptactionhank/atlassian-confluence:6.3.4

Thanks for helping.

Kind regards,

Flavio

<img width="380" alt="error" src="https://user-images.githubusercontent.com/28959963/34584355-c4d86022-f19b-11e7-823a-5a3cc660902f.PNG">
<img width="532" alt="error_1" src="https://user-images.githubusercontent.com/28959963/34584361-ca5cb39a-f19b-11e7-9753-cfa32d62507b.PNG">
<img width="715" alt="error_2" src="https://user-images.githubusercontent.com/28959963/34584365-cf0ceca2-f19b-11e7-8170-829c4ee28d1d.PNG">

**Comment by meyerf99** [comment]
No one can help me?

Kind regards, Flavio

**Comment by cptactionhank** [comment]
I'm not sure why you ask  here and not on Atlassian Answers for JIRA support.

```
OAuth mismatch
The application link was attempting to authenticate with the remote application but the OAuth configuration is not the same at both ends of the application link. For example, if you wish to use impersonation, then both the local and remote ends of the link must be set to use impersonation.
```

* https://confluence.atlassian.com/kb/oauth-troubleshooting-guide-719095274.html#OAuthTroubleshootingGuide-OAuthmismatch
* https://confluence.atlassian.com/applinks/oauth-security-for-application-links-774045732.html
