### ISSUE TITLE
Documentation seems to have a lot of random words in it

### ISSUE THREAD

**Issue by djpain** [cptactionhank/docker-atlassian-jira#58]
Hey it seems this url has a lot of random words from "configuring system properties". Even when I browse using a private browser. 

https://cptactionhank.github.io/docker-atlassian-jira/

**Comment by zimmerru** [comment]
I noticed this some time ago, given the words I wouldn't think they would be there by design for SEO or keyword purposes.. but I could be wrong.

**Comment by cptactionhank** [comment]
Funny lorem ipsum generator went unfunny and confusing. Unfortunately I do not have that much time free time to write nicer documentation.
