### ISSUE TITLE
Should the install dir be a volume?

### ISSUE THREAD

**Issue by soupdiver** [cptactionhank/docker-atlassian-jira#6]
I'm thinking about if the `JIRA_INSTALL ` directory should be a volume or not.
I've got a data-only container which is also based on this image.
Since `JIRA_INSTALL ` **and** `JIRA_HOME ` are volumes I can't upgrade my JIRA container and reuse my data container because the old install folder would be reused.
So I have to export the data and recreate everything to upgrade JIRA.

So maybe it would be better to not use `JIRA_INSTALL ` as a volume.

What do you think about this? Or correct me if I'm wrong :)

**Comment by cptactionhank** [comment]
The reason I have done this, and forgive me if i'm wrong is that there happening file changes when running JIRA in that directory and you'd might want these to survive. If making changes to the templates as far as I know, also is changes in the installation directory and not home directory.

I don't know if you can "after mount" the installation directory as a volume if one would need said changes, but if we can it might be a good idea to remove the installation directory as a volume, and then "advanced" users can add an `-v /usr/local/atlassian/jira`; I'm just unsure what exact changes to files actually occurs when running an instance, there for sure are some log files, but other than that?

**Comment by soupdiver** [comment]
Yeah I like the approach to manually add the volume when running the container. So we can have the best of both approaches.
And yeah JIRA (as well as Confluence) kinda mix install dir and data dir stuff which makes it sometimes complicated to use it inside Docker.
I'm also no professional in using these apps but I recently had to migrate JIRA/Confluence to Docker and ran into **a lot of** issues.

So I would be +1 on removing the volume from the Dockerfile and add documentation to add the volume during container start time

**Comment by cptactionhank** [comment]
It's been carried out in the 6.3.15, 6.4, 6.4.1, and 6.4.2, this will be backported to earlier versions as well
