### ISSUE TITLE
JIRA raises file permission error since 7.7.2

### ISSUE THREAD

**Issue by int128** [cptactionhank/docker-atlassian-jira#61]
JIRA shows the following error on upgrading from 7.7.1 to 7.7.2.

> Setup: JIRA couldn't create the jira.home directory
> Ensure JIRA has permission to create and write to the jira.home directory `/var/atlassian/jira`.
Review our documentation for more information on setting your JIRA home.

It seems the ID of running user `daemon` has been changed from `1` to `2` since 7.7.2, maybe due to `alpine` image.

I fixed owner of files under `/var/atlassian/jira` by the following command and JIRA works fine.

```sh
chown daemon:daemon -R /var/atlassian/jira
```

It would be nice if this change is documented.

Thank you for the great work.

**Comment by apertureless** [comment]
Experiencing the same after upgrading  to `7.8.0` 

The premissions for `/var/atlassian/jira` inside the docker container are also pretty weird.

```
bash-4.4$ cd /var/atlassian/jira
bash-4.4$ ls -la
total 180
drwxr-xr-x   12 bin      bin           4096 Feb 27 08:51 .
drwxr-xr-x    3 root     root          4096 Feb 20 23:21 ..
drwxr-xr-x    2 bin      bin           4096 Oct  5 08:14 analytics-logs
-rw-r--r--    1 bin      bin            112 Aug  5  2016 atlassian-jira-security.log
drwxr-xr-x    6 bin      bin           4096 Sep 22 08:14 caches
drwx------    4 bin      bin           4096 Feb 26  2016 data
-rw-r--r--    1 bin      bin           1047 Aug  5  2016 dbconfig.xml
drwxr-xr-x    3 bin      bin         122880 Feb 27 08:21 export
drwxr-xr-x    4 bin      bin           4096 Oct  5 08:17 import
-rw-r--r--    1 bin      bin            278 Oct  5 08:37 jira-healthcheck-eol.json
drwxr-xr-x    2 bin      bin           4096 Jan  7 18:11 log
drwx------    2 bin      bin           4096 May 23  2017 logos
drwxr-xr-x    2 bin      bin           4096 Aug  5  2016 monitor
drwx------    6 bin      bin           4096 Feb 25  2016 plugins
drwxr-xr-x    3 bin      bin           4096 Aug  5  2016 tmp
```

**Comment by Maelstromeous** [comment]
@apertureless Did you do the chown command from within the container or the host?

**Comment by mendhak** [comment]
@Maelstromeous I was able to run that command from the host.  Doing that got my Jira upgrade working, without it  the logs were full of file system access failures.  

    sudo chown -R 2:2 /mypath/jira
