### ISSUE TITLE
Running jira as https

### ISSUE THREAD

**Issue by hassanakhtar** [cptactionhank/docker-atlassian-jira#62]
I am trying to run the docker as

`docker run --detach --name "jira-prod" \
    --publish "8080:8080" \
    --env "CATALINA_OPTS=-Xms1024m -Xmx1024m -Datlassian.plugins.enable.wait=300" \
    --env "X_PROXY_NAME=jira.domain.com" \
    --env "X_PROXY_SCHEME=https" \
    --env "X_PROXY_PORT=443" \
    cptactionhank/atlassian-jira:latest`

But I can still access the instance on http and not https. Am I doing something wrong or misconfiguring somehow? I am using nginx on front, but my understanding is that it should at least run on: https://IP:PORT and then i will point my FQDN to this specific port using nginx.

Thanks a lot for the great docker image. :+1:

**Comment by cptactionhank** [comment]
I think your NGINX configuration is wrong and your env flags looks right. It works on my machine(tm) just fine

**Comment by hassanakhtar** [comment]
Yeah if we keep NGINX aside, it should at least work with http**s**://<IP:PORT>, but it is working as http://<IP:PORT>

**Comment by hassanakhtar** [comment]
Thanks, the configurations and all were correct. My bad that the server's firewall was blocking the port.
