### ISSUE TITLE
ENV JIRA_VERSION in Dockerfile wrong?

### ISSUE THREAD

**Issue by martin-gerdes** [cptactionhank/docker-atlassian-jira#63]
https://hub.docker.com/r/cptactionhank/atlassian-jira/~/dockerfile/ lists:
ENV JIRA_VERSION 7.2.0-RC01

This is apparently incorrect.
Could this be corrected, since the ENV variable is presumably being used somewhere?

Other than just running the container, how can I ascertain from the web pages which jira version I get when pulling cptactionhank/atlassian-jira:latest? (I had presumed that I could use that ENV variable...)

(Alternatively the dockerfile at that URL could just be out of date, of course. The questions of either fixing that, or an alternative means of determining the version stay the same either way.)

**Comment by martin-gerdes** [comment]
I have precisely the same issue with the Confluence Dockerfile by the way... (https://hub.docker.com/r/cptactionhank/atlassian-confluence/~/dockerfile/ lists 6.0.0-rc5)

**Comment by cptactionhank** [comment]
It's a Docker Hub thing, for some reason Docker Hub displays the contents of the `eap` branch and not `master`. If you either run the container you should see the tags matches the versions and `latest` matches the daily latest version.

**Comment by martin-gerdes** [comment]
Thank you a lot. That hint, that my link is showing the wrong version, was enough for me to solve my problem:
I just have to use
https://github.com/cptactionhank/docker-atlassian-jira/blob/master/Dockerfile
https://github.com/cptactionhank/docker-atlassian-confluence/blob/master/Dockerfile

and use the JIRA_VERSION / CONF_VERSION from those. :-)

I see that you removed the original links I provided (they are showing a 404 page now), so you also removed the nasty trap mine for others.

With that I would say: closed.
