### ISSUE TITLE
jira cannot connect to marketpalce while running in container

### ISSUE THREAD

**Issue by iahmad-khan** [cptactionhank/docker-atlassian-jira#64]
Hi , 

I have proxy config set on the host , when I run jira in docker it cannot connect to marketplace , even when I do net=host.

Do I need to insert the http proxy info somewhere in jira configurations?

I am not yet sure about jira , but facing the same problem in confluence dockerization a week ago , I had to put the proxy info into catalina.properties.

thanks

**Comment by cptactionhank** [comment]
Check for example your base path or ask around on Atlassian Answers.

https://confluence.atlassian.com/upm/problems-connecting-to-the-atlassian-marketplace-273875718.html

**Comment by iahmad-khan** [comment]
Hi , 

It was the proxy issue. 

I just set the proxy settings at end of the file catalina.properties and it worked. 

cheers
ijaz
