### ISSUE TITLE
JIRA NullPointerException error

### ISSUE THREAD

**Issue by XenoPhage** [cptactionhank/docker-atlassian-jira#66]
Since moving to 7.8.0 with alpine, we're getting NullPointerException errors when displaying some gadgets on dashboards.  Googling around, it appears this may be directly related to openjdk in alpine.

https://community.atlassian.com/t5/Jira-Software-questions/Error-500-when-generating-charts-after-upgrading-from-7-6-3-to-7/qaq-p/739967

**Comment by dpash** [comment]
I believe this is related to #65 and missing fonts. I assume you have the same stack trace?

    java.lang.NullPointerException
       at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)

**Comment by cptactionhank** [comment]
Updated the Alpine based versions

**Comment by XenoPhage** [comment]
UGH ..  I put this in the wrong github project.  Meant for jira-software, not just jira..  I'll re-create over there.
