### ISSUE TITLE
runing in a persistent manner

### ISSUE THREAD

**Issue by kaldown** [cptactionhank/docker-atlassian-jira#67]
How to run an image and not re-configure jira after each restart?
I read documentation, realizing a very small part of it.
Could it be more strict forward explanation with a examples, please?

Just didn't get, where it stores state, if running from an image as you described:
`docker run --detach --publish 8080:8080 cptactionhank/atlassian-jira:latest`

Thanks

**Comment by cptactionhank** [comment]
1. Don't use dockerized Atlassian JIRA if you are not sure how to operate either JIRA or Docker
2a. remount the autogenerated mount
2b. mount the the jira home folder to your host

**Comment by matejkramny** [comment]
@cptactionhank it's not at all obvious and should be mentioned on the readme
