### ISSUE TITLE
Jira 7.9.0 availability

### ISSUE THREAD

**Issue by bobswift** [cptactionhank/docker-atlassian-jira#70]
Jira 7.9.0 has just become available. It looks like there is an automated builder that finds, changes, and commits the update of the Jira version. How and when does that get kicked off?

**Comment by cptactionhank** [comment]
IFTTT kicks off a CircleCI build of the master branch on a daily basis, have a look at the circle.yml and related scripts. Docker Hub auto tags branch to tag ie. `master`->`latest` and `x.x.x`->`x.x.x`

**Comment by bobswift** [comment]
Nice. Thank you for the explanation! The image appeared shortly after my request, so it was available very quickly after the Atlassian release :).
