### ISSUE TITLE
Unable to connect to external postgres database

### ISSUE THREAD

**Issue by DRoet** [cptactionhank/docker-atlassian-jira#71]
Using:
jira version: 7.9.2
postgres: 10.3 or 10.2 (official docker image)

Hi, 

I am somehow unable to connect to an external postgres database within the Jira setup.
It keeps throwing an error about the postgres:jdbc driver ("Something unusual has occured"), are external databases not supported in this image?

thanks

**Comment by Achimh3011** [comment]
I use Postgres 9.3 with Jira in a second container and it works fine. 

Postgres versions > 10 are (AFAIK) not officially supported by Jira, so my guess would be that what you see is not a problem of the docker image.

**Comment by DRoet** [comment]
@Achimh3011 whoops, good call. I had must've had the wrong support page open. 9.6 is indeed the latest supported version for postgres w/ Jira. 

that explains it, thanks!
