### ISSUE TITLE
Increase JVM max memory

### ISSUE THREAD

**Issue by davidwmartines** [cptactionhank/docker-atlassian-jira#73]
Hi, we are getting `java.lang.OutOfMemoryError: GC overhead limit exceeded` every couple weeks.  We have >42k issues, and have read that bumping up the jvm memory from 768MB might help.  I see we need to edit **/opt/atlassian/jira/bin/setenv.sh**.  How would you recommend adding this configurability from an env var, to edit this file?

Thanks

**Comment by cptactionhank** [comment]
use the environment variable `CATALINA_OPTS` to set these e.g. `-e CATALINA_OPTS='-Xmx4G'`

**Comment by salzamt** [comment]
hey @cptactionhank 
thanks for this answer, took me quiet some time to find this, could you maybe add this to the docs? that would help a lot :)
