### ISSUE TITLE
Jira 8.0 EAP Builds

### ISSUE THREAD

**Issue by MeikTranel** [cptactionhank/docker-atlassian-jira#77]
With the announcement of Jira 8.0 EAP Versions at Atlassian Summit Barcelona 2018 it'd be quite cool to be able to take a peak at 8.0. This would mean updating the EAP branches to the new 8.0-EAP02 listed here:

https://www.atlassian.com/software/jira/download-eap

**Comment by cptactionhank** [comment]
Thank you. 

Note this might revert to a previous version depending on Atlassian's JSON feed for latest EAP version.
